# default config
baseurl = "https://blog.curso-r.com/"
languageCode = "pt-br"
title = "Blog | Curso-R"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
publishdir = "docs"
disqusShortname = "curso-r-com"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "css/custom.css"
[[params.plugins.css]]
link = "css/github.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "js/highlight.pack.js"

# navigation

[[menu.main]]
name = "Blog"
url = "#"
weight = 1

[[menu.main]]
name = "Cursos"
url = "https://www.curso-r.com/cursos"
weight = 2

[[menu.main]]
name = "Fórum"
url = "https://discourse.curso-r.com/"
weight = 3

[[menu.main]]
name = "Curso-R"
url = "https://www.curso-r.com"
weight = 4

# deult parameter
[params]
logo = "images/logo.png"
footerLogo = "images/footerLogo.png"
home = "Home"
footerImage = "images/footerImage.jpg"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "Este é o blog da Curso-R. Aqui você encontra tutoriais, análises de temas cotidianos e tudo o mais que o maravilhoso universo do R tem a nos oferecer."
# Preloader
preloader = true
# search
search = true
# about author
author = "Curso-R"
author_image = "images/banner-img.png"
bio = "Este é o blog da Curso-R. Aqui você encontra tutoriais, análises de temas cotidianos e tudo o mais que o maravilhoso universo do R tem a nos oferecer."
# Contact info
email = "contato@curso-r.com"
address = "[Acesse nosso fórum](https://discourse.curso-r.com/)"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "UA-87272102-2"
# copyright
copyright = "Copyright &copy; 2021 Curso-R"

# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site

[[params.social]]
icon = "ti-github"
url = "https://github.com/curso-r"


[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/curso_r"

[[params.social]]
icon = "ti-instagram"
url = "https://www.instagram.com/cursoo_r/"

[[params.social]]
icon = "ti-linkedin"
url = "https://br.linkedin.com/company/curso-r"

[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/cursodeR/"

# Authors

[[params.authors]]
name = "Athos"
link = "https://twitter.com/athos_damiani"

[[params.authors]]
name = "Beatriz Milz"
link = "https://twitter.com/BeaMilz"

[[params.authors]]
name = "Caio"
link = "https://www.linkedin.com/in/clente"

[[params.authors]]
name = "Daniel"
link = "https://twitter.com/dfalbel"

[[params.authors]]
name = "Fernando"
link = "https://twitter.com/Azeloc"

[[params.authors]]
name = "Julio"
link = "https://twitter.com/jtrecenti"

[[params.authors]]
name = "William"
link = "https://wamorim.com/"
