---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)

library(magrittr)
```

```{r}
yaml_to_tibble <- function(file) {
  rmarkdown::yaml_front_matter(file) |> 
    purrr::map(paste, collapse = "|") |> 
    tibble::as_tibble() |> 
    dplyr::mutate(arquivo = file)
}

grafico_freq <- function(tab, var) {
  tab |> 
    dplyr::pull({{var}}) |> 
    stringr::str_split(pattern = "\\|") |>
    purrr::flatten_chr() |> 
    tibble::enframe("name", "variavel") |> 
    dplyr::count(variavel) |> 
    dplyr::mutate(variavel = forcats::fct_reorder(variavel, n)) |> 
    ggplot2::ggplot(ggplot2::aes(x = n, y = variavel)) +
    ggplot2::geom_col(fill = "orange") +
    ggplot2::geom_label(ggplot2::aes(label = n)) +
    ggplot2::theme_minimal() +
    ggplot2::labs(y = "", x = "Frequência")
}
```

```{r}
arquivos <- list.files("content/posts/", pattern = ".Rmd$", full.names = TRUE)

tab <- arquivos |> 
  purrr::map_dfr(yaml_to_tibble) |>  
  dplyr::filter(is.na(draft) | draft == "FALSE") |> 
  dplyr::mutate(categories = tolower(categories)) |> 
  dplyr::mutate(author = stringr::str_replace(author, "Beatriz Milz", "Beatriz"))
```

## Número de posts: `r dplyr::n_distinct(tab$arquivo)`

## Por autoria

```{r}
grafico_freq(tab, author)
```

## Por categoria

```{r}
grafico_freq(tab, categories)
```

## Por ano

```{r}
tab |> 
  dplyr::mutate(
    date = as.Date(date),
    ano = lubridate::year(date)
  ) |> 
  grafico_freq(ano) +
  ggplot2::coord_flip() +
  ggplot2::scale_y_discrete(limits = as.character(2017:lubridate::year(Sys.Date())))
```


## Por mês/ano

```{r}
tab |> 
  dplyr::mutate(
    date = as.Date(date),
    ano = lubridate::year(date),
    mes = lubridate::month(date),
    mes_ano = lubridate::make_date(ano, mes, 1)
  ) |> 
  dplyr::count(mes_ano) |> 
  ggplot2::ggplot(ggplot2::aes(x = mes_ano, y = n)) +
  ggplot2::geom_col(fill = "orange") +
  ggplot2::theme_minimal() +
  ggplot2::labs(x = "", y = "Frequência")
```

## Por mês

```{r}
tab |> 
  dplyr::mutate(
    date = as.Date(date),
    mes = lubridate::month(date)
  ) |> 
  grafico_freq(mes) +
  ggplot2::coord_flip() +
  ggplot2::scale_y_discrete(limits = as.character(1:12))
```

## Autoria vs categoria

```{r}
tab |> 
  dplyr::filter(!stringr::str_detect(author, "\\|")) |> 
  dplyr::group_by(author) |> 
  dplyr::filter(dplyr::n() >= 10) |> 
  dplyr::count(author, categories) |> 
  ggplot2::ggplot(ggplot2::aes(x = n, y = author)) +
  ggplot2::geom_col(fill = "orange") +
  ggplot2::facet_wrap(dplyr::vars(categories)) +
  ggplot2::theme_minimal() +
  ggplot2::labs(y = "", x = "Frequência")
```

## Posts aposentados

```{r}
tab |> 
  dplyr::filter(retired == "TRUE") |> 
  dplyr::select(date, title, author) |> 
  knitr::kable()
```

